In [1]:
import numpy as np

# numpy의 기반 데이터타입 => ndarray

## array

In [2]:
a = [[1, 2, 1], [3, 4, 2]]

In [3]:
a = np.array(a)

## shape

In [4]:
a.shape

(2, 3)

## ndim

In [5]:
a.ndim

2

## dtype

In [6]:
a.dtype

dtype('int32')

## astype

In [7]:
b = a.astype('float64')

In [8]:
b.dtype

dtype('float64')

## arange

In [9]:
sequence_array = np.arange(10)

In [10]:
sequence_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
sequence_array.dtype

dtype('int32')

In [12]:
sequence_array.shape

(10,)

## zeros

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
zeros_array = np.zeros((2,2), dtype='int32') # dtype 지정해주지 않으면 default인 float64 지정됨
zeros_array

array([[0, 0],
       [0, 0]])

In [15]:
zeros_array.dtype

dtype('int32')

## ones

In [16]:
np.ones((2,))

array([1., 1.])

In [17]:
ones_array = np.ones((1, 3)) # dtype 지정해주지 않으면 default인 float64 지정됨
ones_array

array([[1., 1., 1.]])

In [18]:
ones_array.dtype

dtype('float64')

## reshape

In [19]:
a = np.arange(10)

In [20]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
np.zeros((2,3), dtype='int32').reshape(-1) # -1로 1차원 변환 가능

array([0, 0, 0, 0, 0, 0])

In [23]:
np.zeros((2, 6), dtype='int32').reshape(4, -1) # -1로 4행 몇열로 구성해야하는지 알아서 계산

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## tolist

In [24]:
np.ones((2, 3), dtype='int32').tolist() # ndarray 자료형을 list로 변환

[[1, 1, 1], [1, 1, 1]]

In [25]:
np.arange(8).reshape(2, 2, 2).reshape(-1, 1) # 3차원 데이터 2차원으로 변환

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [26]:
np.arange(8).reshape(-1, 1) # 1차원 데이터 2차원으로 변환

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

## Indexing, Slicing (연속된 인덱스를 추출하는 것이 Slicing)

### 1. 단일값 추출

In [27]:
array1 =  np.arange(1, 10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
array1[2]

3

In [29]:
array1[0] = 8

In [30]:
array1

array([8, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
array2 = np.arange(10).reshape(5, -1)
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
array2[2][1]

5

In [33]:
array2[2, 1]

5

In [34]:
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### 2. 슬라이싱

In [35]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
array[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
array[3:6]

array([3, 4, 5])

In [38]:
array = np.arange(9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
array[:,:]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
array[1:, 1:]

array([[4, 5],
       [7, 8]])

In [41]:
array[2, 1:]

array([7, 8])

In [42]:
array[:, 0]

array([0, 3, 6])

### 3. 팬시 인덱싱

In [43]:
array = np.arange(9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
array[[0,1], 2]

array([2, 5])

In [45]:
array[[0,1], 1:]

array([[1, 2],
       [4, 5]])

### 4. 불린 인덱싱

In [46]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [48]:
array[array > 3]

array([4, 5, 6, 7, 8, 9])

## sort

### 1. np.sort() => 원 행렬 그대로 유지한 채 정렬된 행렬 반환

In [49]:
array = np.array([1,3,2,4])
array

array([1, 3, 2, 4])

In [60]:
np.sort(array)

array([1, 2, 3, 4])

In [61]:
np.sort(array)[::-1]

array([4, 3, 2, 1])

In [51]:
array

array([1, 3, 2, 4])

### 2. ndarray.sort() => 원 행렬 변환하며 None 반환

In [52]:
array2 = np.array([1,3,4,2,6,5])
array2

array([1, 3, 4, 2, 6, 5])

In [53]:
array2.sort()

In [62]:
array2

array([1, 2, 3, 4, 5, 6])

In [76]:
array2[::-1]

array([6, 5, 4, 3, 2, 1])

In [77]:
array2

array([1, 2, 3, 4, 5, 6])

In [55]:
print(array2.sort())

None


- 2차원 정렬 (axis)

In [79]:
array = np.array([[12, 8], [7, 3]])
array

array([[12,  8],
       [ 7,  3]])

In [80]:
np.sort(array)

array([[ 8, 12],
       [ 3,  7]])

In [81]:
np.sort(array, axis=0)

array([[ 7,  3],
       [12,  8]])

In [82]:
np.sort(array, axis=1)

array([[ 8, 12],
       [ 3,  7]])

In [83]:
array.sort(axis=0)

### 3. argsort() => 원본 행렬의 정렬 시 행렬 인덱스 반환, 어떤 순서로 뽑아야 정렬이 되는가?

In [99]:
array = np.array([1, 4, 5, 3])
array

array([1, 4, 5, 3])

In [102]:
np.sort(array)

array([1, 3, 4, 5])

In [106]:
np.argsort(array)

array([0, 3, 1, 2], dtype=int64)

In [101]:
np.argsort(array)[::-1]

array([2, 1, 3, 0], dtype=int64)

- argsort 응용

In [108]:
name = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score = np.array([78, 95, 84, 98, 88])

In [110]:
idx = np.argsort(score)
idx

array([0, 2, 4, 1, 3], dtype=int64)

In [113]:
print(f'성적 오름차순 정렬 시 name: {name[idx]}')

성적 오름차순 정렬 시 name: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## 선형대수 연산

### dot (행렬 내적 = 행렬 곱)

In [114]:
a = np.arange(1, 7).reshape(2, -1)
b = np.arange(7, 13).reshape(3, -1)

In [115]:
np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

### 전치행렬 (행과 열 위치 변환)

In [117]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])